server:
  port: 8082

math.max: 100

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring.application.name: math
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5671/eureka
